# fly.toml app configuration file generated for combinedapp on 2024-06-19T14:23:18+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'combinedapp'
primary_region = 'arn'

[build]

[env]
  BACKEND_PORT = '3003'

[processes]
  app = 'node index.js'

[http_service]
  internal_port = 3003
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.http_checks]]
    interval = 10000
    timeout = 2000
    path = "/health"
    protocol = "http"