name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:

  check_style:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint


  deployment_pipeline:
    needs: [check_style]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: 5.0
          mongodb-replica-set: test-rs
          mongodb-port: 42069

      - name: Set MongoDB connection string
        run: echo "MONGODB_URI=mongodb://localhost:42069" >> $GITHUB_ENV

      - name: Set MongoDB test connection string
        run: echo "TEST_MONGODB_URI=mongodb://localhost:42069/test" >> $GITHUB_ENV

      - name: Set secret
        run: echo "SECRET=${{ secrets.SECRET }}" >> $GITHUB_ENV

      - name: Set backend port
        run: echo "BACKEND_PORT=3003" >> $GITHUB_ENV

      - name: Set frontend port
        run: echo "PORT=3000" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install
      - name: Builds
        run: npm run build

      - name: Run server tests
        run: npm run test:server
        env:
          CI: true

      - name: Run client tests
        run: npm run test:client
        env:
          CI: true

      - name: start server
        run: npm run start:server &

      - name: cypress e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run cypress:run
          start: npm run start
          wait-on: http://localhost:3000


      - name: Deploy the app to Fly.io
        if: ${{ github.event_name == 'push' && !contains(join(fromJSON(toJson(github.event.commits.*.message)), ' '), '#skip') }}
        uses: actions/checkout@v4

      - name: Setup Flyctl
        if: ${{ github.event_name == 'push' && !contains(join(fromJSON(toJson(github.event.commits.*.message)), ' '), '#skip') }}
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy with Flyctl
        if: ${{ github.event_name == 'push' && !contains(join(fromJSON(toJson(github.event.commits.*.message)), ' '), '#skip') }}
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}


  tag_release:
      needs: [deployment_pipeline]
      runs-on: ubuntu-20.04
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Bump version and push tag
          if: ${{ github.event_name == 'push' && !contains(join(fromJSON(toJson(github.event.commits.*.message)), ' '), '#skip') }}
          uses: anothrNick/github-tag-action@1.68.0
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            DEFAULT_BUMP: patch
